{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "MoT Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operation Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "replica_state" }
   ]
  },
  {
   "title": "Replication status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "replica_sync_status" }
   ]
  },
  { "title": "OS monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU usage trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance!=\"\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "instance CPU"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance!=\"\"} - node_memory_MemAvailable_bytes{instance!=\"\"}) / node_memory_MemTotal_bytes{instance!=\"\"}) * 100",
     "legendFormat": "instance memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance!=\"\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance!=\"\"} - node_memory_MemAvailable_bytes{instance!=\"\"}) / node_memory_MemTotal_bytes{instance!=\"\"}) * 100",
     "legendFormat": "instance memory"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_filesystem_size_bytes{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Storage usage trend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{} -node_filesystem_free_bytes{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype!=\"\",instance!=\"\"} - node_filesystem_free_bytes{fstype!=\"\",instance!=\"\"} )/ node_filesystem_size_bytes{fstype!=\"\",instance!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Containers monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Containers statuses",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{ __name__!~\".*time_seconds.*|.*push_failure.*\", job=\"container_status\", pushgateway_instance=\"container_status\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU usage trend per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage trend per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum(rate(container_memory_usage_bytes{name != ''}[1m])) BY (instance, name) * 100) / on(instance) group_left() (sum by (instance) (machine_cpu_cores))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received network traffic per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name!=\"\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent network traffic per container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Postgres monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Replication Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_replica_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replication lag trend",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pg_replication_lag{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Returned",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname!=\"\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Connections trend",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname!=\"\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetched trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname!=\"\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Inserted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname!=\"\"}  !=0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname!=\"\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname!=\"\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}