//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Israel Standard Time")]
        public string TimeZone {
            get {
                return ((string)(this["TimeZone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int Interval {
            get {
                return ((int)(this["Interval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          [\r\n          {\r\n          \"ProcessName\": \"NanoLockSec.Services.Storag" +
            "e\",\r\n          \"CommandLine\": \"cd c:\\\\NanoLock\\\\DataStoreService\\r\\nstart /min \\" +
            "\"DataStore Service\\\" dotnet NanoLockSec.Services.Storage.dll\",\r\n          \"Displ" +
            "ayName\": \"DataStore Service\"\r\n          },\r\n           {\r\n          \"ProcessName" +
            "\": \"NanoLockSec.Services.DeviceKeyStore\",\r\n          \"CommandLine\": \"cd c:\\\\Nano" +
            "Lock\\\\DeviceKeyStore\\r\\nstart /min \\\"Device Key Store\\\" dotnet NanoLockSec.Servi" +
            "ces.DeviceKeyStore.dll\",\r\n          \"DisplayName\": \"Device Key Store\"\r\n         " +
            " },\r\n          {\r\n          \"ProcessName\": \"NanoLockSec.Services.DeviceAuthentic" +
            "ation\",\r\n          \"CommandLine\": \"cd c:\\\\NanoLock\\\\DeviceAuthentication\\r\\nstar" +
            "t /min \\\"Device Authentication\\\" dotnet NanoLockSec.Services.DeviceAuthenticatio" +
            "n.dll\",\r\n          \"DisplayName\": \"Device Authentication\"\r\n          },\r\n       " +
            "   {\r\n          \"ProcessName\": \"NanoLockSec.Services.Devices\",\r\n          \"Comma" +
            "ndLine\": \"cd c:\\\\NanoLock\\\\DeviceServices\\r\\nstart /min \\\"Device Service\\\" dotne" +
            "t NanoLockSec.Services.Devices.dll\",\r\n          \"DisplayName\": \"Device Service\"\r" +
            "\n          },\r\n          {\r\n          \"ProcessName\": \"NanoLockSec.Services.OverT" +
            "heAir\",\r\n          \"CommandLine\": \"cd c:\\\\NanoLock\\\\OTAServer\\r\\nstart /min \\\"OT" +
            "A Service\\\" dotnet NanoLockSec.Services.OverTheAir.dll\",\r\n          \"DisplayName" +
            "\": \"OTA Service\"\r\n          },\r\n          {\r\n          \"ProcessName\": \"NanoLockS" +
            "ec.Services.Management.Api\",\r\n          \"CommandLine\": \"cd c:\\\\NanoLock\\\\Managem" +
            "entAPI\\r\\nstart /min \\\"Management API\\\" dotnet NanoLockSec.Services.Management.A" +
            "pi.dll\",\r\n          \"DisplayName\": \"Management API\"\r\n          },\r\n          {\r\n" +
            "          \"ProcessName\": \"NanoLockSec.Services.Data.DataReadyProcessor\",\r\n      " +
            "    \"CommandLine\": \"cd c:\\\\NanoLock\\\\DataReadyProcessor\\r\\nstart /min \\\"Data Rea" +
            "dy Processor\\\" dotnet NanoLockSec.Services.Data.DataReadyProcessor.dll\",\r\n      " +
            "    \"DisplayName\": \"Data Ready Processor\"\r\n          },\r\n          {\r\n          " +
            "\"ProcessName\": \"NanoLockSec.Services.Alerts\",\r\n          \"CommandLine\": \"cd c:\\\\" +
            "NanoLock\\\\AlertsManagement\\r\\nstart /min \\\"Alerts Management\\\" dotnet NanoLockSe" +
            "c.Services.Alerts.dll\",\r\n          \"DisplayName\": \"Alerts Management\"\r\n         " +
            " },\r\n          {\r\n          \"ProcessName\": \"NanoLockSec.Services.Extensibility\"," +
            "\r\n          \"CommandLine\": \"cd c:\\\\NanoLock\\\\ExtensibilityService\\r\\nstart /min " +
            "\\\"Extensibility Service\\\" dotnet NanoLockSec.Services.Extensibility.dll\",\r\n     " +
            "     \"DisplayName\": \"Extensibility Service\"\r\n          },\r\n          {\r\n        " +
            "  \"ProcessName\": \"NanoLockSec.Services.Configuration\",\r\n          \"CommandLine\":" +
            " \"cd c:\\\\NanoLock\\\\ConfigurationService\\r\\nstart /min \\\"Configuration Service\\\" " +
            "dotnet NanoLockSec.Services.Configuration.dll\",\r\n          \"DisplayName\": \"Confi" +
            "guration Service\"\r\n          },\r\n          {\r\n          \"ProcessName\": \"NanoLock" +
            "Sec.Services.Identity\",\r\n          \"CommandLine\": \"cd c:\\\\NanoLock\\\\IdentityServ" +
            "ice\\r\\nstart /min \\\"Identity Service\\\" dotnet NanoLockSec.Services.Identity.dll\"" +
            ",\r\n          \"DisplayName\": \"Identity Service\"\r\n          }\r\n          ]\r\n      " +
            "  ")]
        public string Processes {
            get {
                return ((string)(this["Processes"]));
            }
        }
    }
}
